"""Local transport token for the Jarvis daemon API.

Localhost binding is not authentication: any local process (including a
browser page issuing fetch() to 127.0.0.1) can reach the API. Mutating
endpoints therefore require a shared local token, generated by jarvisd and
readable only by the owning user. Design: docs/MACOS_PERMISSION_MODEL.md §5.
"""

from __future__ import annotations

import hmac
import os
import secrets
from pathlib import Path


API_TOKEN_FILENAME = "api-token"
API_TOKEN_HEADER = "X-Jarvis-Token"
_API_TOKEN_FILE_MODE = 0o600


class TransportTokenError(Exception):
    """Raised when the API token cannot be created or read safely."""


def api_token_path(runtime_dir: Path) -> Path:
    return runtime_dir / API_TOKEN_FILENAME


def ensure_api_token(runtime_dir: Path) -> str:
    """Return the API token, generating and persisting one when missing."""

    token_path = api_token_path(runtime_dir)
    existing = load_api_token(runtime_dir)
    if existing is not None:
        return existing

    token = secrets.token_hex(32)
    try:
        fd = os.open(
            token_path,
            os.O_WRONLY | os.O_CREAT | os.O_TRUNC,
            _API_TOKEN_FILE_MODE,
        )
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(token + "\n")
        os.chmod(token_path, _API_TOKEN_FILE_MODE)
    except OSError as exc:
        raise TransportTokenError(f"Cannot write API token file: {token_path}") from exc
    return token


def load_api_token(runtime_dir: Path) -> str | None:
    """Return the persisted API token, or None when absent or empty."""

    token_path = api_token_path(runtime_dir)
    try:
        raw = token_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise TransportTokenError(f"Cannot read API token file: {token_path}") from exc

    token = raw.strip()
    return token or None


def verify_api_token(expected: str | None, provided: str | None) -> bool:
    """Constant-time token comparison; missing values always fail."""

    if not expected or not provided:
        return False
    return hmac.compare_digest(expected.encode("utf-8"), provided.encode("utf-8"))


__all__ = [
    "API_TOKEN_FILENAME",
    "API_TOKEN_HEADER",
    "TransportTokenError",
    "api_token_path",
    "ensure_api_token",
    "load_api_token",
    "verify_api_token",
]
