"""Import smoke tests for the Prompt 01 Jarvis scaffold."""

from __future__ import annotations

import importlib


MODULES = (
    "jarvis",
    "jarvis.cli",
    "jarvis.config",
    "jarvis.paths",
    "jarvis.logging",
    "jarvis.daemon",
    "jarvis.daemon.app",
    "jarvis.daemon.lifecycle",
    "jarvis.daemon.state_machine",
    "jarvis.runtime",
    "jarvis.runtime.supervisor",
    "jarvis.runtime.models",
    "jarvis.api",
    "jarvis.api.routes_health",
    "jarvis.api.routes_state",
    "jarvis.api.routes_events",
    "jarvis.api.routes_input",
    "jarvis.api.routes_brain",
    "jarvis.api.routes_voice",
    "jarvis.api.routes_audio",
    "jarvis.api.routes_runtime",
    "jarvis.api.routes_workers",
    "jarvis.api.routes_memory",
    "jarvis.api.routes_tools",
    "jarvis.api.websocket",
    "jarvis.store",
    "jarvis.store.db",
    "jarvis.store.migrations",
    "jarvis.store.event_store",
    "jarvis.store.repositories",
    "jarvis.events",
    "jarvis.events.types",
    "jarvis.events.models",
    "jarvis.events.bus",
    "jarvis.turns",
    "jarvis.turns.models",
    "jarvis.turns.repository",
    "jarvis.turns.orchestrator",
    "jarvis.turns.policies",
    "jarvis.brain",
    "jarvis.brain.base",
    "jarvis.brain.manager",
    "jarvis.brain.context_builder",
    "jarvis.brain.mock_adapter",
    "jarvis.brain.claude_cli_adapter",
    "jarvis.brain.codex_cli_adapter",
    "jarvis.brain.openai_adapter",
    "jarvis.memory",
    "jarvis.memory.manager",
    "jarvis.memory.summarizer",
    "jarvis.memory.retrieval",
    "jarvis.memory.policies",
    "jarvis.audio",
    "jarvis.audio.models",
    "jarvis.audio.devices",
    "jarvis.audio.policy",
    "jarvis.voice",
    "jarvis.voice.models",
    "jarvis.voice.queue",
    "jarvis.voice.broker",
    "jarvis.voice.tts",
    "jarvis.voice.stt",
    "jarvis.voice.vad",
    "jarvis.voice.anti_echo",
    "jarvis.voice.listening",
    "jarvis.tools",
    "jarvis.tools.registry",
    "jarvis.tools.permissions",
    "jarvis.tools.shell_tool",
    "jarvis.tools.file_tool",
    "jarvis.tools.system_tool",
    "jarvis.workers",
    "jarvis.workers.jobs",
    "jarvis.workers.broker",
    "jarvis.workers.worker_events",
    "jarvis.workers.codex_worker",
    "jarvis.workers.claude_worker",
    "jarvis.workers.mock_worker",
    "jarvis.panel",
    "jarvis.panel.menubar_app",
    "jarvis.panel.webview_bridge",
)


def test_every_required_python_module_imports() -> None:
    for module_name in MODULES:
        importlib.import_module(module_name)
