#!/usr/bin/env bash
# Manual launchd install for the official com.ozzy.jarvisd agent
# (LAUNCH_SUPERVISION.md §5, FROZEN). This script is run deliberately by a
# human and NEVER by any build, test, or smoke step. Without --yes it only
# prints the plan and exits.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

LABEL="com.ozzy.jarvisd"
JARVIS_HOME="$HOME/.jarvis"
WRAPPER_SRC="$REPO_ROOT/scripts/jarvisd"
WRAPPER_DST="$JARVIS_HOME/bin/jarvisd"
PLIST_SRC="$REPO_ROOT/launchd/$LABEL.plist.example"
PLIST_DST="$HOME/Library/LaunchAgents/$LABEL.plist"
DOMAIN="gui/$(id -u)"

APPLY=0
if [ "${1:-}" = "--yes" ]; then
  APPLY=1
elif [ -n "${1:-}" ]; then
  echo "Usage: $0 [--yes]" >&2
  exit 2
fi

cat <<PLAN
Jarvis launchd install plan (label: $LABEL)
============================================
This will do EXACTLY the following, nothing else:

  1. mkdir -p $JARVIS_HOME/bin $JARVIS_HOME/logs $JARVIS_HOME/runtime
  2. Generate the wrapper $WRAPPER_DST
     from $WRAPPER_SRC with JARVIS_REPO pinned to $REPO_ROOT
     (launchd must not read scripts under ~/Documents - ADR-014).
  3. Generate $PLIST_DST
     from $PLIST_SRC (__HOME__ -> $HOME).
  4. launchctl bootstrap $DOMAIN $PLIST_DST
  5. Print 'launchctl print $DOMAIN/$LABEL' so you can verify.

It will NOT touch $JARVIS_HOME/jarvis.db, existing logs, or the API token.
PLAN

if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
  echo ""
  echo "ERROR: $LABEL is already loaded in $DOMAIN." >&2
  echo "Run scripts/uninstall-launchd.sh first; this script never stacks agents." >&2
  exit 1
fi

if [ "$APPLY" -ne 1 ]; then
  echo ""
  echo "Dry run only - nothing was changed. Re-run with --yes to apply."
  exit 0
fi

echo ""
echo "Applying..."

mkdir -p "$JARVIS_HOME/bin" "$JARVIS_HOME/logs" "$JARVIS_HOME/runtime"

{
  printf '#!/bin/sh\n'
  printf '# Generated by scripts/install-launchd.sh - do not edit; edit scripts/jarvisd in the repo.\n'
  printf 'JARVIS_REPO="%s"\n' "$REPO_ROOT"
  printf 'export JARVIS_REPO\n'
  printf 'exec "%s" "$@"\n' "$WRAPPER_SRC"
} >"$WRAPPER_DST.tmp"
# The installed wrapper is a thin absolute-path shim; the logic stays in the
# repo wrapper so there is a single source of truth for how jarvisd starts.
mv "$WRAPPER_DST.tmp" "$WRAPPER_DST"
chmod 755 "$WRAPPER_DST"
echo "Wrapper installed: $WRAPPER_DST"

sed "s|__HOME__|$HOME|g" "$PLIST_SRC" >"$PLIST_DST.tmp"
mv "$PLIST_DST.tmp" "$PLIST_DST"
chmod 644 "$PLIST_DST"
echo "Plist installed: $PLIST_DST"

launchctl bootstrap "$DOMAIN" "$PLIST_DST"
echo "Agent bootstrapped in $DOMAIN."

echo ""
echo "Verify with:"
echo "  launchctl print $DOMAIN/$LABEL | head -20"
echo "  curl -s http://127.0.0.1:41741/health"
echo ""
echo "NOTE (ADR-014 / TCC): the wrapper executes the venv python inside the"
echo "repo under ~/Documents. If the daemon does not come up and"
echo "$JARVIS_HOME/logs/jarvisd.err.log shows a permission or 'operation not"
echo "permitted' error, grant access per docs/runbooks/LAUNCHD.md."
