#!/usr/bin/env bash
# Manual launchd install for the official com.dan.dand agent
# (LAUNCH_SUPERVISION.md §5, FROZEN). This script is run deliberately by a
# human and NEVER by any build, test, or smoke step. Without --yes it only
# prints the plan and exits.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

LABEL="com.dan.dand"
DAN_HOME="$HOME/.dan"
WRAPPER_SRC="$REPO_ROOT/scripts/dand"
WRAPPER_DST="$DAN_HOME/bin/dand"
PLIST_SRC="$REPO_ROOT/launchd/$LABEL.plist.example"
PLIST_DST="$HOME/Library/LaunchAgents/$LABEL.plist"
DOMAIN="gui/$(id -u)"

APPLY=0
if [ "${1:-}" = "--yes" ]; then
  APPLY=1
elif [ -n "${1:-}" ]; then
  echo "Usage: $0 [--yes]" >&2
  exit 2
fi

cat <<PLAN
DAN launchd install plan (label: $LABEL)
============================================
This will do EXACTLY the following, nothing else:

  1. mkdir -p $DAN_HOME/bin $DAN_HOME/logs $DAN_HOME/runtime
  2. Generate the wrapper $WRAPPER_DST
     from $WRAPPER_SRC with DAN_REPO pinned to $REPO_ROOT
     (launchd must not read scripts under ~/Documents - ADR-014).
  3. Generate $PLIST_DST
     from $PLIST_SRC (__HOME__ -> $HOME).
  4. launchctl bootstrap $DOMAIN $PLIST_DST
  5. Print 'launchctl print $DOMAIN/$LABEL' so you can verify.

It will NOT touch $DAN_HOME/dan.db, existing logs, or the API token.
PLAN

if launchctl print "$DOMAIN/$LABEL" >/dev/null 2>&1; then
  echo ""
  echo "ERROR: $LABEL is already loaded in $DOMAIN." >&2
  echo "Run scripts/uninstall-launchd.sh first; this script never stacks agents." >&2
  exit 1
fi

if [ "$APPLY" -ne 1 ]; then
  echo ""
  echo "Dry run only - nothing was changed. Re-run with --yes to apply."
  exit 0
fi

echo ""
echo "Applying..."

mkdir -p "$DAN_HOME/bin" "$DAN_HOME/logs" "$DAN_HOME/runtime"

{
  printf '#!/bin/sh\n'
  printf '# Generated by scripts/install-launchd.sh - do not edit; edit scripts/dand in the repo.\n'
  printf 'DAN_REPO="%s"\n' "$REPO_ROOT"
  printf 'export DAN_REPO\n'
  printf 'PATH="$HOME/.local/bin:$HOME/.homebrew/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"\n'
  printf 'export PATH\n'
  printf 'if [ -z "${DAN_CONFIG:-}" ] && [ -f "$HOME/.dan/config.toml" ]; then\n'
  printf '  DAN_CONFIG="$HOME/.dan/config.toml"\n'
  printf '  export DAN_CONFIG\n'
  printf 'fi\n'
  printf 'PYTHON="$DAN_REPO/.venv/bin/python"\n'
  printf 'if [ ! -x "$PYTHON" ]; then\n'
  printf '  PYTHON="$(command -v python3)"\n'
  printf 'fi\n'
  printf 'if [ -n "${DAN_CONFIG:-}" ]; then\n'
  printf '  DAN_CONFIG_REAL="$("$PYTHON" - "$DAN_CONFIG" <<'\''PY'\''\n'
  printf 'import sys\n'
  printf 'from pathlib import Path\n'
  printf '\n'
  printf 'print(Path(sys.argv[1]).expanduser().resolve(strict=False))\n'
  printf 'PY\n'
  printf ')"\n'
  printf '  DAN_EXAMPLE_REAL="$("$PYTHON" - "$DAN_REPO/config/dan.example.toml" <<'\''PY'\''\n'
  printf 'import sys\n'
  printf 'from pathlib import Path\n'
  printf '\n'
  printf 'print(Path(sys.argv[1]).expanduser().resolve(strict=False))\n'
  printf 'PY\n'
  printf ')"\n'
  printf '  if [ "$DAN_CONFIG_REAL" = "$DAN_EXAMPLE_REAL" ]; then\n'
  printf '    echo "config/dan.example.toml is not a runtime config." >&2\n'
  printf '    echo "Use ~/.dan/config.toml or $DAN_REPO/config/dan.toml." >&2\n'
  printf '    exit 1\n'
  printf '  fi\n'
  printf 'fi\n'
  printf 'cd "$DAN_REPO" || exit 126\n'
  printf 'exec "$PYTHON" -m dan.cli daemon run "$@"\n'
} >"$WRAPPER_DST.tmp"
# The installed wrapper lives outside ~/Documents so launchd does not need to
# execute repo-local scripts that can be blocked by macOS document privacy.
mv "$WRAPPER_DST.tmp" "$WRAPPER_DST"
chmod 755 "$WRAPPER_DST"
echo "Wrapper installed: $WRAPPER_DST"

sed "s|__HOME__|$HOME|g" "$PLIST_SRC" >"$PLIST_DST.tmp"
mv "$PLIST_DST.tmp" "$PLIST_DST"
chmod 644 "$PLIST_DST"
echo "Plist installed: $PLIST_DST"

launchctl bootstrap "$DOMAIN" "$PLIST_DST"
echo "Agent bootstrapped in $DOMAIN."

echo ""
echo "Verify with:"
echo "  launchctl print $DOMAIN/$LABEL | head -20"
echo "  curl -s http://127.0.0.1:41741/health"
echo ""
echo "NOTE (ADR-014 / TCC): the wrapper executes the venv python inside the"
echo "repo under ~/Documents. If the daemon does not come up and"
echo "$DAN_HOME/logs/dand.err.log shows a permission or 'operation not"
echo "permitted' error, grant access per docs/runbooks/LAUNCHD.md."
