#!/usr/bin/env bash
# The single human entrypoint for installing the DAN runtime into $HOME.
#
#   scripts/install.sh --stage-only   render + verify in a temp staging root,
#                                     change NO active home path (CI/dry run)
#   scripts/install.sh --no-launchd   complete install into $HOME but do not
#                                     write or bootstrap the launchd agent
#   scripts/install.sh                full install; launchd bootstrap is still
#                                     a separate deliberate step, see below
#
# The installer is backup-first and reversible: every replaced path is copied
# into ~/.dan/backups/install-<stamp>/ and listed with before/after SHA in
# ~/.dan/install-manifest.json. It never touches ~/.claude/archive (excluded
# structurally) and it never deletes ~/.dan/dan.db, owner data or migration
# backups. This script does NOT run launchctl; bootstrapping the agent stays
# a deliberate human step via scripts/install-launchd.sh --yes.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DAN_HOME="$HOME/.dan"

STAGE_ONLY=0
NO_LAUNCHD=0
for arg in "$@"; do
  case "$arg" in
    --stage-only) STAGE_ONLY=1 ;;
    --no-launchd) NO_LAUNCHD=1 ;;
    *)
      echo "Usage: $0 [--stage-only] [--no-launchd]" >&2
      exit 2
      ;;
  esac
done

# Python used for the installer itself: repo venv, then ~/.dan/venv, then python3.
PYTHON="${DAN_PYTHON:-}"
if [ -z "$PYTHON" ]; then
  for candidate in "$REPO_ROOT/.venv/bin/python" "$DAN_HOME/venv/bin/python"; do
    if [ -x "$candidate" ]; then PYTHON="$candidate"; break; fi
  done
fi
if [ -z "$PYTHON" ]; then
  PYTHON="$(command -v python3)"
fi

run_installer() {
  ( cd "$REPO_ROOT" && PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}" "$PYTHON" -m dan.install "$@" )
}

if [ "$STAGE_ONLY" -eq 1 ]; then
  echo "Stage-only: render + verify in a temporary staging root (no home changes)."
  if [ "$NO_LAUNCHD" -eq 1 ]; then
    run_installer --stage-only --no-launchd
  else
    run_installer --stage-only
  fi
  exit 0
fi

echo "Installing DAN runtime from: $REPO_ROOT"
echo "Target HOME:                 $HOME"

mkdir -p "$DAN_HOME/bin" "$DAN_HOME/logs" "$DAN_HOME/runtime"

# 1. Product virtualenv with the decreed extras.
if [ ! -x "$DAN_HOME/venv/bin/python" ]; then
  echo "Creating $DAN_HOME/venv ..."
  "$(command -v python3)" -m venv "$DAN_HOME/venv"
fi
echo "Installing the checkout (editable, [voice,panel]) ..."
"$DAN_HOME/venv/bin/pip" install --quiet --upgrade pip
"$DAN_HOME/venv/bin/pip" install --quiet -e "$REPO_ROOT[voice,panel]"

# 2. CLI wrappers outside ~/Documents (ADR-014 / TCC).
write_wrapper() {
  local target="$1" module_args="$2"
  {
    printf '#!/bin/sh\n'
    printf '# Generated by scripts/install.sh - edit the repo, not this file.\n'
    printf 'DAN_REPO="%s"\n' "$REPO_ROOT"
    printf 'export DAN_REPO\n'
    printf 'if [ -z "${DAN_CONFIG:-}" ] && [ -f "$HOME/.dan/config.toml" ]; then\n'
    printf '  DAN_CONFIG="$HOME/.dan/config.toml"\n'
    printf '  export DAN_CONFIG\n'
    printf 'fi\n'
    printf 'exec "%s" -m %s "$@"\n' "$DAN_HOME/venv/bin/python" "$module_args"
  } >"$target.tmp"
  chmod 755 "$target.tmp"
  mv "$target.tmp" "$target"
  echo "Wrapper: $target"
}
write_wrapper "$DAN_HOME/bin/dan" "dan.cli"
write_wrapper "$DAN_HOME/bin/dand" "dan.cli daemon run"

# 3. Product config seed (never overwrites an existing runtime config).
if [ ! -f "$DAN_HOME/config.toml" ]; then
  echo "NOTE: no $DAN_HOME/config.toml yet - copy config/dan.example.toml and edit it."
fi

# 4. Adapters, managed blocks and the single launchd plist go through the
#    atomic Python installer (staged, verified, backup-first).
if [ "$NO_LAUNCHD" -eq 1 ]; then
  run_installer --apply --no-launchd
else
  run_installer --apply
fi

echo ""
echo "Done. Install manifest: $DAN_HOME/install-manifest.json"
if [ "$NO_LAUNCHD" -eq 1 ]; then
  echo "Launchd was skipped (--no-launchd)."
else
  echo "Plist installed. To load the agent deliberately, run:"
  echo "  scripts/install-launchd.sh --yes"
fi
echo "Uninstall (manifest-scoped, keeps dan.db/owner/migration backups):"
echo "  scripts/uninstall.sh"
